In [2]:
# Swmi Shreeji

Advance Numpy

In [4]:
import numpy as np

In [7]:
# NumPy arrays are called homogeneous because all elements must have the same data type.
sales = np.array([100,120,130,150])
print(f"Sales      : {sales}")
print(f"Shape      : {sales.shape}")
print(f"Data Type  : {sales.dtype}")
print(f"Dimension  : {sales.ndim}")

Sales      : [100 120 130 150]
Shape      : (4,)
Data Type  : int64
Dimension  : 1


In [11]:
a = [100, 120, 130, 150]
b = [80, 90, 100, 110]
c =  [90, 95, 100, 105]
sales_matrix = np.array([a,b,c])
print(f"Sales Matrix : \n\n{sales_matrix}\n\n")
print(f"Shape        : {sales_matrix.shape}")
print(f"Data Type    : {sales_matrix.dtype}")
print(f"Dimension    : {sales_matrix.ndim}")

Sales Matrix : 

[[100 120 130 150]
 [ 80  90 100 110]
 [ 90  95 100 105]]


Shape        : (3, 4)
Data Type    : int64
Dimension    : 2


In [12]:
# np.zeros() - np.zeros(shape) creates an array filled with zeros.
zeros_array = np.zeros(4) # Float - Data Type
print(f"Zeros Array : {zeros_array}")
print(f"Shape       : {zeros_array.shape}")
print(f"Data Type   : {zeros_array.dtype}")

Zeros Array : [0. 0. 0. 0.]
Shape       : (4,)
Data Type   : float64


In [13]:
# Integer Data Type
zeros_array = np.zeros(4,dtype=int) 
print(f"Zeros Array : {zeros_array}")
print(f"Shape       : {zeros_array.shape}")
print(f"Data Type   : {zeros_array.dtype}")

Zeros Array : [0 0 0 0]
Shape       : (4,)
Data Type   : int64


In [16]:
# np.ones() - np.ones(shape) creates an array filled with ones.
ones = np.ones((2,3))
print(f"Ones Array  : \n\n{ones}\n\n")
print(f"Shape       : {ones.shape}")
print(f"Data Type   : {ones.dtype}")
print(f"Dimension   : {ones.ndim}")

Ones Array  : 

[[1. 1. 1.]
 [1. 1. 1.]]


Shape       : (2, 3)
Data Type   : float64
Dimension   : 2


In [26]:
# np.arange() - np.arange(start, stop, step) works like Python’s range() but returns a NumPy array.
q1 = np.arange(1, 5)
print(f"Quaters (1,5)     :  {q1}")
q2 = np.arange(10,20,2)
print(f"Quaters (10,20,2) :  {q2}")
q3 = np.arange(1,100,5)
print(f"Quaters (1,100,5) :  {q3}")

Quaters (1,5)     :  [1 2 3 4]
Quaters (10,20,2) :  [10 12 14 16 18]
Quaters (1,100,5) :  [ 1  6 11 16 21 26 31 36 41 46 51 56 61 66 71 76 81 86 91 96]


In [29]:
# np.linspace() - np.linspace(start, stop, num) creates evenly spaced values between start and stop.
f1 = np.linspace(1,5,2)
print(f"Fractions 1 (1,5,2)   :  {f1}")
f2 = np.linspace(10,20,2)
print(f"Fractions 2 (10,20,2) :  {f2}")
f3 = np.linspace(1,100,5)
print(f"Fractions 3 (1,100,5) :  {f3}")

Fractions 1 (1,5,2)   :  [1. 5.]
Fractions 2 (10,20,2) :  [10. 20.]
Fractions 3 (1,100,5) :  [  1.    25.75  50.5   75.25 100.  ]


In [30]:
sales_matrix

array([[100, 120, 130, 150],
       [ 80,  90, 100, 110],
       [ 90,  95, 100, 105]])

In [38]:
print(f"First Row - First Column   : {sales_matrix[0, 0]}")
print(f"Second Row - Third Column  : {sales_matrix[1, 2]}")
print(f"Accessing Entire Rows      : {sales_matrix[0]}")
print(f"Accessing Entire Columns   : {sales_matrix[:, 1]}\n")
print(f"Slicing Arrays : \n\n{sales_matrix[0:2, 1:3]}\n")

First Row - First Column   : 100
Second Row - Third Column  : 100
Accessing Entire Rows      : [100 120 130 150]
Accessing Entire Columns   : [120  90  95]

Slicing Arrays : 

[[120 130]
 [ 90 100]]



In [39]:
one = np.array([10, 20, 30])
two = np.array([1, 2, 3])
print(f"Array Operations")
print(f"Addition        : {one+two}")
print(f"Subtraction     : {one-two}")
print(f"Multiplication  : {one*two}")
print(f"Division        : {one/two}")
print(f"Reminder        : {one%two}")

Array Operations
Addition        : [11 22 33]
Subtraction     : [ 9 18 27]
Multiplication  : [10 40 90]
Division        : [10. 10. 10.]
Reminder        : [0 0 0]


Statistical Functions

In [42]:
print(f"Sales               : {sales}")
print(f"Mean                : {np.mean(sales)}")
print(f"Median              : {np.median(sales)}")
print(f"Standard Deviation  : {np.std(sales)}")
print(f"Minimum             : {np.min(sales)}")
print(f"Maximum             : {np.max(sales)}")
print(f"Sumation            : {np.sum(sales)}")

Sales               : [100 120 130 150]
Mean                : 125.0
Median              : 125.0
Standard Deviation  : 18.027756377319946
Minimum             : 100
Maximum             : 150
Sumation            : 500


In [43]:
# Axis in NumPy - In data science, calculations are often performed row-wise or column-wise.
print(f"Sales Matrix     : \n\n{sales_matrix}\n\n")
print(f"Column-Wise Sum  : {np.sum(sales_matrix, axis=0)}")
print(f"Row-Wise Sum     : {np.sum(sales_matrix, axis=1)}")

Sales Matrix     : 

[[100 120 130 150]
 [ 80  90 100 110]
 [ 90  95 100 105]]


Column-Wise Sum  : [270 305 330 365]
Row-Wise Sum     : [500 380 390]


In [49]:
# Reshape
numbers = np.array([1,2,3,4,5,6])
reshaped = numbers.reshape(2,3)
print(f"Original Numbers : {numbers}\n")
print(f"Reshaped Numbers : \n\n{reshaped}")

Original Numbers : [1 2 3 4 5 6]

Reshaped Numbers : 

[[1 2 3]
 [4 5 6]]


In [51]:
# Random Numbers - Random data is important for simulations and machine learning.
random_data = np.random.randint(1, 100, 10)
print(f"Random Data          : {random_data}")
print(f"Random Decimal Data  : {np.random.rand(5)}")

Random Data          : [15 82  3 72 81  3  7 33 32 27]
Random Decimal Data  : [0.13410771 0.46420847 0.42739938 0.29964245 0.25668193]


In [52]:
# Matrix Operations
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print(A + B)

[[ 6  8]
 [10 12]]


In [57]:
# Unique Values
value = np.array([1,2,4,2,3,3,3])
print(f"Original Values       : {value}")
print(f"Unique Values         : {np.unique(value)}")
print(f"Sort Values           : {np.sort(value)}")
print(f"Conditional Selection : {np.where(value > 2)}")

Original Values       : [1 2 4 2 3 3 3]
Unique Values         : [1 2 3 4]
Sort Values           : [1 2 2 3 3 3 4]
Conditional Selection : (array([2, 4, 5, 6]),)


Jay Swaminarayan - Thank You